### ISSUE TITLE
`kotlinx-datetime` should be an `api` dependency

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/kmp-passenger-api#3]
Becase we expose the `kotlinx.datetime.LocalDateTime` class of it via the `TimeOffsetProvider` it should be available at the compile time classpath.
https://github.com/ioki-mobility/kmp-passenger-api/blob/5d2d474a71a44aee0b556e297ff01497ae0a7287/library/src/commonMain/kotlin/com/ioki/passenger/api/TimeOffsetProvider.kt#L3-L7

**Comment by vhontar** [comment]
Changed here: https://github.com/ioki-mobility/kmp-passenger-api/pull/5
