### ISSUE TITLE
Replace `wrapper-validation-action` with just `wrapper-validation`

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/kmp-passenger-api#4]
When runnin on github action, we see these information:
![Screenshot 2024-08-06 at 1 46 43 PM](https://github.com/user-attachments/assets/d231bb22-1d11-47f0-a942-c6ba7bb661cc)

We should do that 😅 

👉  https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlewrapper-validation-action-has-been-replaced-by-gradleactionswrapper-validation

**Comment by vhontar** [comment]
Changed here: https://github.com/ioki-mobility/kmp-passenger-api/pull/6
